### ISSUE TITLE
Adimen artifiziala: Search

### ISSUE THREAD

**Issue by KepaUrzelai** [landakoop/landabus#3]
1. Travelling salesman problema (problema del viajante) begiratu/moldatu.
2. Gure bilaketa algoritmoa eraiki.

**Comment by inigoarenaza** [comment]
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwiC_tq09pziAhVj6uAKHfT8CZoQFjABegQIBRAC&url=http%3A%2F%2Fopenaccess.uoc.edu%2Fwebapps%2Fo2%2Fbitstream%2F10609%2F59085%2F7%2FmgenovardTFM1216memoria.pdf&usg=AOvVaw14mNm2v5QqoFTBOjjYpiaV
