### ISSUE TITLE
Telegram bot apiarekin konkurrentzia arazoak

### ISSUE THREAD

**Issue by KepaUrzelai** [landakoop/landabus#7]
Taldekide bakoitzak docker abiaraztean telegrameko bot apia duen kontenedorea ere iniziatzen da, eta ondorioz botera egiten diren konexioetan talka edo konkurrentzia arazoak ematen dira.

**Comment by bingenGalartza** [comment]
Hemendik aurrera Telegram bota erabili nahi denean betiko komandoei `-f docker-compose.yml -f docker-compose-override.yml` gehitu beharko zaie. Adibidez:
Pizteko
`docker-compose -f docker-compose.yml -f docker-compose-override.yml up -d`
Itzaltzeko
`docker-compose -f docker-compose.yml -f docker-compose-override.yml down`
